---
title: "Getting data ready for analysis"
output: html_notebook
---

Obtain a treedata object for anatomical entities in catfish

```{r}
library(rphenoscape)
library(treeplyr)
library(RCurl)
library(rjson)
library(readr)
library(urltools)
library(pracma)
library(httr)


nex <- pk_get_ontotrace_xml(taxon = c("Siluriformes"), entity = "anatomical entity")

m <- pk_get_ontotrace(nex)
m$taxa <- gsub(" ", "_", m$taxa)
write.csv(m, file="~/repos/ontologyPCM/data/Ontotrace_Siluriformes_AnatomicalEntity.csv")

tree <- read.tree("~/repos/ontologyPCM/data/actinopt_12k_treePL.tre")
td <- make.treedata(tree, m)

saveRDS(td, "~/repos/ontologyPCM/data/tdSiluriformesAnatomicalEntity.rds")
```

```{r}
td <- readRDS("~/repos/ontologyPCM/data/tdSiluriformesAnatomicalEntity.rds")
td
```

Get semantic similarity matrix

```{r}
traits <- colnames(td$dat)
traits <- traits[-(1:2)] #delete otu data
traits
```

Get IRI ids for each trait.

```{r}
traitDetails <- lapply(traits, function(x) pk_anatomical_detail(x, verbose=TRUE))
```

```{r}
traitDetails[1:5]
traitIDs <- unname(do.call(c, sapply(traitDetails, function(x) x[,'@id'])))
```

```{r}
irisPhenotypes <- sapply(traitIDs, url_encode)
```


```{r}
filename <- "../output/siluriformesFormData.txt"

cat("iris=%5B%0A%20%20", file=filename)
irisPhenotypes <- lapply(irisPhenotypes, function(x) gsub("/", "%2F", x, fixed=TRUE))
irisPhenotypes <- lapply(irisPhenotypes, function(x) gsub(":", "%3A", x, fixed=TRUE))
irisPhenotypes <- lapply(irisPhenotypes, function(x) gsub("=", "%3D%0A", x, fixed=TRUE))
dum <- lapply(irisPhenotypes[1:(length(irisPhenotypes)-1)],function(x) cat(paste0('%22', x,'%22%2C', sep=""), file=filename, append=TRUE))
cat(paste0('%22', irisPhenotypes[[length(irisPhenotypes)]],'%22',"%5D%0A", sep=""), file=filename, append=TRUE)
```


```{r}

api.semanticSimilarity_query <- "curl -X POST -d @../output/siluriformesFormData.txt 'http://kb.phenoscape.org/api/similarity/jaccard'"
semanticSimilarityAPIResults <- system(api.semanticSimilarity_query, intern=TRUE)

```

```{r}

results <- fromJSON(semanticSimilarityAPIResults)
scores <- lapply(results$results, function(x) x$score)
scores <- sapply(scores, function(x) if(is.null(x)) NA else(x))
result_terms <- do.call(rbind, lapply(results$results, function(x) do.call(cbind, lapply(x$terms, curlUnescape))))
semanticSimilarityMatrix <- matrix(NA, nrow=length(irisPhenotypes), ncol=length(irisPhenotypes))
diag(semanticSimilarityMatrix) <- 1
rownames(semanticSimilarityMatrix) <- colnames(semanticSimilarityMatrix) <- curlUnescape(irisPhenotypes)

for(i in 1:nrow(result_terms)){
  semanticSimilarityMatrix[result_terms[i,1], result_terms[i,2]] <- semanticSimilarityMatrix[result_terms[i,2], result_terms[i,1]] <- scores[i]
}

rownames(semanticSimilarityMatrix) <- colnames(semanticSimilarityMatrix) <- traits

write.csv(semanticSimilarityMatrix, file="../output/siluriformesSemanticSimMatrix.csv")

```

Check to see if semantic similarity matrix makes sense.

```{r}
maxSS <- list()
for(i in 1:ncol(semanticSimilarityMatrix)){
  ss <- semanticSimilarityMatrix[-i,]
  j <- which(ss[,i]==max(ss[,i]))[1]
  maxSS[[i]] <- cbind(colnames(semanticSimilarityMatrix)[i], rownames(ss)[j], round(ss[j, i],4))
}
maxSS <- do.call(rbind, maxSS)
as.data.frame(maxSS)


minSS <- list()
for(i in 1:ncol(semanticSimilarityMatrix)){
  ss <- semanticSimilarityMatrix[-i,]
  j <- which(ss[,i]==min(ss[,i]))[1]
  minSS[[i]] <- cbind(colnames(semanticSimilarityMatrix)[i], rownames(ss)[j], round(ss[j, i],4))
}
minSS <- do.call(rbind, minSS)
as.data.frame(minSS)

```

Neighbor-joining tree of SS matrix
```{r}
njt <- nj(1-semanticSimilarityMatrix)
pdf("../output/njTreeSiluriformesSemanticMatrix.pdf", height=30, width=30)
plot(njt, type="unrooted", cex=0.35)
dev.off()
```



